### ISSUE TITLE
base64 -D

### ISSUE THREAD

**Issue by holmboe** [wildducktheories/y2j#2]
Trying to install using the instructions in the README I get the following error:

```
nn@host:~ $ ./y2j.sh installer ~/bin | bash
/usr/bin/base64: invalid option -- 'D'
Try `/usr/bin/base64 --help' for more information.
Installed /home/nn/bin/{y2h.sh,y2j,j2y,yq}.
nn@host:~ $ 
```

This is on Ubuntu 12.04. The issue seems to be here: 
https://github.com/wildducktheories/y2j/blob/e69d17888d14c3b6b64332da0ab462650005b5ea/y2j.sh#L50

**Comment by jonseymour** [comment]
Henrik,

Thanks for the report. I've adjusted the installation script to cope with differences in how the base64 decode option is specified between Linux and BSD variants (e.g. OSX). You will likely want to pull the updated wildducktheories/y2j docker image from the docker registry with `docker pull` or rebuild it yourself.

Let me know if this doesn't fix it for you.
